### ISSUE TITLE
Analyser dependency 5.2.0

### ISSUE THREAD

**Issue by redDwarf03** [kiwi-bop/intl_generator#18]
Hello
is it possible to publish a new version to pub.dev with analyzer 5.2.0 instead of : ">=4.0.0 <5.0.0"
Thank you

**Comment by ilyachange** [comment]
Same question here.
As it's already pull request available https://github.com/kiwi-bop/intl_generator/pull/17, any chance that it going to be merged in the near future? 
Thank you.

**Comment by jaumard** [comment]
Done on 0.4.0 :)
